# Generated by Django 5.0.6 on 2024-07-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='derivation',
            field=models.JSONField(null=True),
        ),
    ]
