# Generated by Django 5.0.6 on 2024-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_remove_answer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='generative_model',
            field=models.CharField(choices=[('claude-3-haiku-20240307', 'CLAUDE_3_HAIKU'), ('gpt-3.5-turbo', 'GPT_3_5_TURBO'), ('gemini-1.5-flash', 'GEMINI_1_5_FLASH'), ('gemini-1.5-pro', 'GEMINI_1_5_PRO')], default='claude-3-haiku-20240307', max_length=50),
        ),
    ]
